version: '3.8'
services:
  shipping-app:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: spring_shipping_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/shipping_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - general

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - general

  postgresqldb:
    image: 'postgres:13.1-alpine'
    container_name: postgresqldb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shipping_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - general

networks:
  general:
    driver: bridge